services:
  nginx:
    image: nginx:1.27.3-alpine3.20
    restart: always
    networks:
      - mst-internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro  
      - ./webroot:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

networks:
  mst-internal:
    name: mastodon-internal
    external: true